package com.joinmatch.backend.enums;

public enum NotificationType {
    FRIEND_REQUEST,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    EVENT_INVITE,
    EVENT_UPDATE,
    EVENT_CANCELLED,
    TEAM_REQUEST,
    TEAM_REQUEST_ACCEPTED,
    TEAM_REQUEST_REJECTED,
    TEAM_LEFT,
    TEAM_CANCELED, POST_COMMENT, POST_REACTION, COMMENT_REACTION, COMMENT_REPLY, TEAM_MEMBER_REMOVED,
    EVENT_INVITATION, EVENT_JOIN_REQUEST, EVENT_JOIN_ACCEPTED, EVENT_JOIN_REJECTED, EVENT_JOINED_PUBLIC, EVENT_INVITATION_ACCEPTED,
    EVENT_INVITATION_REJECTED,
    EVENT_CANCELED

    }

